import "./globals.css";
import { locales } from '@root/config'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return locales.map((lng) => ({ lng }))
}

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng}>
      <body >{children}</body>
    </html>
  );
}
