import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng}>
      <body >{children}</body>
    </html>
  );
}
